// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: indexer.sql

package bindings

import (
	"context"
)

const getLastIndexedBlock = `-- name: GetLastIndexedBlock :one
SELECT last_indexed_block
FROM indexer_progress
WHERE version = '1.0'
LIMIT 1
`

func (q *Queries) GetLastIndexedBlock(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getLastIndexedBlock)
	var last_indexed_block string
	err := row.Scan(&last_indexed_block)
	return last_indexed_block, err
}

const updateLastIndexedBlock = `-- name: UpdateLastIndexedBlock :exec
UPDATE indexer_progress
SET 
  last_indexed_block = $1,
  indexed_on = NOW()
WHERE version = '1.0'
`

func (q *Queries) UpdateLastIndexedBlock(ctx context.Context, lastIndexedBlock string) error {
	_, err := q.db.Exec(ctx, updateLastIndexedBlock, lastIndexedBlock)
	return err
}
