// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package bindings

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64
	ThreadID  int64
	Address   string
	Content   string
	IsDeleted bool
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type CommentClosure struct {
	ThreadID int64
	ParentID int64
	ChildID  int64
	Depth    int32
}

type CommentVote struct {
	Address   string
	CommentID int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Vote      int16
}

type Thread struct {
	ID        int64
	Address   string
	Content   string
	IsDeleted bool
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type ThreadVote struct {
	Address   string
	ThreadID  int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Vote      int16
}

type User struct {
	Address   string
	EnsName   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
