// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package bindings

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Challenge struct {
	Address   string
	Message   string
	ExpiresAt int64
}

type Comment struct {
	ID                 int64
	ThreadID           int64
	RepliedToCommentID pgtype.Int8
	Address            string
	Content            string
	ImageFileName      string
	ImageOriginalUrl   string
	ImageThumbnailUrl  string
	Votes              int64
	IsDeleted          bool
	CreatedAt          pgtype.Timestamp
	DeletedAt          pgtype.Timestamp
}

type CommentVote struct {
	Address   string
	CommentID int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Vote      int16
}

type IndexerProgress struct {
	Version          string
	LastIndexedBlock string
	IndexedOn        pgtype.Timestamp
}

type Thread struct {
	ID                int64
	Address           string
	Title             string
	Content           string
	ImageFileName     string
	ImageOriginalUrl  string
	ImageThumbnailUrl string
	Votes             int64
	IsDeleted         bool
	CreatedAt         pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
}

type ThreadVote struct {
	Address   string
	ThreadID  int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Vote      int16
}

type User struct {
	Address           string
	EnsName           pgtype.Text
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	Reputation        int64
	EnsAvatarFileName pgtype.Text
	EnsAvatarUrl      pgtype.Text
}
