// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package bindings

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32
	ThreadID  int32
	Address   string
	Content   string
	IsDeleted bool
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type CommentClosure struct {
	ParentID int32
	ChildID  int32
	Depth    int32
}

type CommentVote struct {
	Address   string
	CommentID int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Vote      int32
}

type Thread struct {
	ID        int32
	Address   string
	Content   string
	IsDeleted bool
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type ThreadVote struct {
	Address   string
	ThreadID  int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Vote      int32
}

type User struct {
	Address   string
	EnsName   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
