// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package bindings

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Challenge struct {
	Address   string
	Message   string
	ExpiresAt int64
}

type Comment struct {
	ID                        int64
	ThreadID                  int64
	RepliedToCommentID        pgtype.Int8
	Address                   string
	Content                   string
	ImageFileName             string
	ImageOriginalUrl          string
	ImageOriginalContentType  string
	ImageFormattedUrl         string
	ImageFormattedContentType string
	Votes                     int64
	IsDeleted                 bool
	CreatedAt                 pgtype.Timestamp
	DeletedAt                 pgtype.Timestamp
}

type CommentVote struct {
	Address   string
	CommentID int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Vote      int16
}

type IndexerProgress struct {
	Version          string
	LastIndexedBlock pgtype.Numeric
	IndexedOn        pgtype.Timestamp
}

type Thread struct {
	ID                        int64
	Address                   string
	Title                     string
	Content                   string
	ImageFileName             string
	ImageOriginalUrl          string
	ImageOriginalContentType  string
	ImageFormattedUrl         string
	ImageFormattedContentType string
	Votes                     int64
	IsDeleted                 bool
	CreatedAt                 pgtype.Timestamp
	DeletedAt                 pgtype.Timestamp
}

type ThreadVote struct {
	Address   string
	ThreadID  int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Vote      int16
}

type Transfer struct {
	BlockNumber   pgtype.Numeric
	TransactionID string
	LogIndex      int64
	FromAddress   string
	ToAddress     string
	Amount        pgtype.Numeric
}

type User struct {
	Address                       string
	EnsName                       pgtype.Text
	CreatedAt                     pgtype.Timestamp
	UpdatedAt                     pgtype.Timestamp
	Reputation                    pgtype.Numeric
	EnsAvatarFileName             pgtype.Text
	EnsAvatarOriginalUrl          pgtype.Text
	EnsAvatarOriginalContentType  pgtype.Text
	EnsAvatarFormattedUrl         pgtype.Text
	EnsAvatarFormattedContentType pgtype.Text
}
