name: lint-test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Go lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./
          args: --enable gocyclo --enable gofmt --enable misspell

      - name: Go test
        run: go test -v ./...
