name: pr-check-indexer

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "*"
      - "!master"

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Go fmt
        run: if [ "$(gofmt -s -l ./indexer | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Go vet
        run: go vet ./indexer/...

      - name: Go build
        run: go build -v ./indexer/...

      - name: Go test
        run: go test -v ./indexer/...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/DockerfileIndexer
          push: false
