name: pr-check

on:
  pull_request:
    branches:
      - "*"
      - "!master"

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Go build api
        run: go build -v ./cmd/api/...

      - name: Go lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./cmd/api
          args: --enable gocyclo --enable gofmt --enable misspell

      - name: Go test
        run: go test -v ./cmd/api/...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/DockerfileApi
          push: false
