name: pr-check-common

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "*"
      - "!master"

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Go fmt
        run: if [ "$(gofmt -s -l ./common | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Go vet
        run: go vet ./common/...

      - name: Go build
        run: go build -v ./common/...

      - name: Go test
        run: go test -v ./common/...
