name: pr-check-api

on:
  pull_request:
    branches:
      - "*"
      - "!master"

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Go fmt
        run: if [ "$(gofmt -s -l ./api | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Go build
        run: go build -v ./api/...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./api
          args: --enable gofmt misspell

      - name: Go test
        run: go test -v ./api/...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/DockerfileApi
          push: false
